apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vantax.fullname" . }}-worker
  labels:
    {{- include "vantax.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      {{- include "vantax.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "vantax.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.image.api }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery", "-A", "workers.celery_app", "worker", "--loglevel=info", "--concurrency=4"]
          envFrom:
            - configMapRef:
                name: {{ include "vantax.fullname" . }}-config
            - secretRef:
                name: {{ include "vantax.fullname" . }}-secret
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
